name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  APP_IMAGE_TAG: ${{ vars.GOOGLE_ARTIFACT_REGISTRY }}/app:${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build and tag Docker image
        run: |
          docker build -t ${{ env.APP_IMAGE_TAG }} -f docker/Dockerfile src/

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Push image to Google Container Registry
        run: |
          gcloud auth configure-docker -q us.gcr.io
          docker push ${{ env.APP_IMAGE_TAG }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to CloudRun
        run: |
           gcloud run deploy my-python-app \
            --image ${{ env.APP_IMAGE_TAG }} \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
